# Generated by Django 4.1.5 on 2023-02-01 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='isJoinable',
            new_name='shared',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='driverID',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='otherInfo',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='shareID',
        ),
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='sharer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='specRequest',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ride',
            name='numPeople',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.IntegerField(choices=[(1, 'Opened'), (2, 'Confirmed'), (3, 'Completed')], default=1),
        ),
    ]
