# Generated by Django 4.1.5 on 2023-02-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_rename_isjoinable_ride_shared_remove_ride_driverid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='time',
        ),
        migrations.AlterField(
            model_name='ride',
            name='date',
            field=models.DateTimeField(help_text='Format: 2023-01-01 12:00'),
        ),
    ]
