# Generated by Django 4.1.5 on 2023-02-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_remove_ride_time_alter_ride_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='vehicleType',
            field=models.CharField(choices=[('SUV', 'SUV'), ('COMPACT', 'COMPACT'), ('F1', 'F1'), ('--', '--')], default='--', max_length=20),
        ),
    ]
