# Generated by Django 4.1.5 on 2023-02-01 23:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride', '0004_alter_ride_vehicletype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='sharer',
        ),
        migrations.AddField(
            model_name='ride',
            name='sharer',
            field=models.ManyToManyField(related_name='share', to=settings.AUTH_USER_MODEL),
        ),
    ]
