# Generated by Django 4.1.5 on 2023-02-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0009_alter_sharerorder_sharerride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='maxPeople',
            field=models.PositiveIntegerField(default=4, help_text='numPeople + allowSharernum'),
        ),
    ]
