# Generated by Django 4.1.5 on 2023-02-02 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=10)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('vehicle_type', models.CharField(choices=[('SUV', 'SUV'), ('COMPACT', 'COMPACT'), ('F1', 'F1'), ('--', '--')], default='COMPACT', max_length=20)),
                ('special_info', models.TextField(blank=True, max_length=200)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
